-- CreateTable
CREATE TABLE "Profile" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "companyName" TEXT NOT NULL DEFAULT 'SHAKTI EXPORTS',
    "gstin" TEXT NOT NULL DEFAULT '24AAAAA0000A1Z5',
    "pan" TEXT NOT NULL DEFAULT 'ABCDE1234F',
    "terms" TEXT NOT NULL DEFAULT 'CREDIT',
    "banker" TEXT NOT NULL DEFAULT 'STATE BANK OF INDIA',
    "accountNo" TEXT NOT NULL DEFAULT '12345678901',
    "ifsc" TEXT NOT NULL DEFAULT 'SBIN0000001',
    "swiftCode" TEXT NOT NULL DEFAULT '',
    "districtOriginCode" TEXT NOT NULL DEFAULT '24',
    "updatedAt" DATETIME NOT NULL
);
